---
title: XSHIP PERFORMANCE (Basic)
runtime: shiny
output: html_document
---
This Basic idea of each tab provided in this tool and detail help ( USER MANUAL ) will be provide in the same . 
 * DASHBOARD
            The window for giving the perception about the number of vessel in each class.and provide the basic information about cargo and Fo consumption over each month on class .


 *VESSEL DETAILS 
            The window for vessel selection and its parameters, its shows the Vessel details and Hydros data and chart. Upload option for upload the new Vessel noon data and its Hydros and User can also enter the vessel parameters manually.
                
 * RAW DATA 
           It shows the Noon data of the selected vessel and also shows the Data distribution over DATE, Power/FO distribution over Speed and SFOC over loads.
           
 * DATA MONITORING  
           The tab provides for filtering the raw data as per the filtering condition, and To shows the filtered data and its distribution chart by pressing the GO Button .
           
 * OPERATING PROFILE 
          The tab provides perception of the selected vessel operating profile over the selected analysis period.
 
 *  PREDICTION 
          It shows the Prediction Power/FO for the filtered Data by our Basic Method.
          
 *  PERFORMANCE CURVE
          It shows the vessel Power/FO curves for various speed and draft for a particular sea state (changeable).
          
 *  VOYAGE CALCULATOR 
           It shows the fuel consumption and Power of the particular voyage calculated based on the input values of speed, draft and distance	.
           
 *  DEVIATION OBSERVATION
           It shows the vessel deviation in percentage error for the input data. By default, its takes the uploaded data other than the analysis period.
           
 *  SEATRIAL COMPARISION 
            The tab shows the vessel performances compare to its Sea trial.
            
 * EEOI/MRV
        Its shows the Calculated EEOI and MRV of the selected vessel for the particular passsage. 
            
 * DOWNLOADS REPORT
            User can download the vessel performances Report as the Excel file by one click.

REMARKS: -
 
 * Download Button provides for downloads the data table in a csv files. 
  
 * Please upload only the provided Templates by editing or CSV files in that format (HEADERS should be same as provided in the templates).


